fanfic_io/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('works/', include('works.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    # ...
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('<slug:username>/', views.profile, name='profile'),
    path('<slug:username>/works/', views.works, name='works'),
    path('<slug:username>/drafts/', views.drafts, name='drafts'),
    path('<slug:username>/bookmarks/', views.bookmarks, name='bookmarks'),
    path('<slug:username>/edit/', views.edit, name='edit'),
    path('<slug:username>/change_username/', views.change_username, name='change_username'),
    path('<slug:username>/change_password/', views.change_password, name='change_password'),
    path('<slug:username>/change_email/', views.change_email, name='change_email'),
]

works/urls.py
from django.urls import path

from . import views

app_name = 'works'
urlpatterns = [
    # .../works/
    path('', views.IndexView.as_view(), name='index'),
    # .../works/5/
    path('<int:story_id>/', views.get_story, name='get_story'),
    # .../works/5/add_bookmark
    path('<int:story_id>/add_bookmark/', views.add_bookmark, name='add_bookmark'),
    # .../works/5/remove_bookmark
    path('<int:story_id>/remove_bookmark/', views.remove_bookmark, name='remove_bookmark'),
    # .../works/5/chapters/1
    path('<int:story_id>/chapters/<int:chapter_number>/', views.get_chapter, name='get_chapter'),
    # .../works/5/characters/1
    path('<int:story_id>/characters/<int:pk>/', views.CharacterView.as_view(), name='get_character'),
    # .../works/new_story
    path('new_story/', views.new_story, name='new_story'),
    # .../works/5/new_chapter
    path('<int:story_id>/new_chapter/', views.new_chapter, name='new_chapter'),
    # .../works/5/new_character
    path('<int:story_id>/new_character/', views.new_character, name='new_character')
]

works/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# TODO: make drafts possible - something with published date maybe?
class Story(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    created_date = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Stories"


class Chapter(models.Model):
    of_story = models.ForeignKey(Story, on_delete=models.CASCADE)
    number = models.IntegerField()
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return str(self.number) + ". " + self.title

    class Meta:
        ordering = ['number']


class Character(models.Model):
    name = models.CharField(max_length=100)
    of_story = models.ForeignKey(Story, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='character_images', blank=True, default='empty.jpg')
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    of_chapter = models.ForeignKey(Chapter,
                                   on_delete=models.CASCADE,
                                   related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.body[:50]

works/forms.py
from django import forms

from .models import Story, Chapter, Character, Comment


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['title', 'description']
        labels = {
            'title': 'Title:',
            'description': 'Short description of the story:'
        }


class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = ['title', 'content']
        labels = {
            'title': 'Title:',
            'content': ''
        }


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name', 'image', 'description']
        labels = {
            'name': 'Full name:',
            'image': 'Picture:',
            'description': 'Short info about the character:'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {
            'body': ''
        }

works/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Story, Chapter, Character
from .forms import StoryForm, ChapterForm, CharacterForm, CommentForm


class IndexView(generic.ListView):
    template_name = 'works/index.html'
    context_object_name = 'stories_list'

    def get_queryset(self):
        return Story.objects.filter().order_by('-created_date')


class StoryView(generic.DetailView):
    model = Story
    template_name = 'works/get_story.html'


class ChapterView(generic.DetailView):
    model = Chapter
    template_name = 'works/get_chapter.html'


def get_story(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if request.method == 'POST':
        request.user.profile.bookmarks.add(story)
        print('Story successful added to bookmarks!')
    context = {
        'story': story,
        'is_author': request.user == story.author
    }
    return render(request, 'works/get_story.html', context)


@login_required
def add_bookmark(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    request.user.profile.bookmarks.add(story)
    return HttpResponseRedirect(reverse('works:get_story', args=[story_id]))


@login_required
def remove_bookmark(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    request.user.profile.bookmarks.remove(story)
    return HttpResponseRedirect(reverse('works:get_story', args=[story_id]))


def get_chapter(request, story_id, chapter_number):
    chapter = get_object_or_404(Chapter,
                                of_story=story_id,
                                number=chapter_number)
    comments = chapter.comments.filter(active=True)
    if request.method != 'POST':
        comment_form = CommentForm()
    else:
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.of_chapter = chapter
            new_comment.author = request.user
            new_comment.save()
            return HttpResponseRedirect(reverse('works:get_chapter', args=[story_id,
                                                                           chapter_number]))
    context = {
        'chapter': chapter,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'works/get_chapter.html', context)


class CharacterView(generic.DetailView):
    model = Character
    template_name = 'works/get_character.html'


@login_required
def new_story(request):
    if request.method != 'POST':
        form = StoryForm()
    else:
        form = StoryForm(request.POST)
        if form.is_valid():
            story = form.save(commit=False)
            story.author = request.user
            story.save()
            return HttpResponseRedirect(reverse('works:index'))

    context = {
        'form': form
    }
    return render(request, 'works/new_story.html', context)


@login_required
def new_chapter(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if story.author != request.user:
        raise Http404
    if request.method != 'POST':
        form = ChapterForm()
    else:
        form = ChapterForm(request.POST)
        if form.is_valid():
            chapter = form.save(commit=False)
            chapter.of_story = story
            chapter.number = Chapter.objects.filter(of_story=story_id).count() + 1
            chapter.save()
            return HttpResponseRedirect(reverse('works:get_story', args=[chapter.of_story.id]))

    context = {
        'form': form,
        'story': story
    }
    return render(request, 'works/new_chapter.html', context)


@login_required
def new_character(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if story.author != request.user:
        raise Http404
    if request.method != 'POST':
        form = CharacterForm()
    else:
        form = CharacterForm(request.POST, request.FILES)
        if form.is_valid():
            character = form.save(commit=False)
            character.of_story = story
            character.save()
            return HttpResponseRedirect(reverse('works:get_story', args=[character.of_story.id]))

    context = {
        'form': form,
        'story': story
    }
    return render(request, 'works/new_character.html', context)

works/templates/works/base.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'works/style.css' %}">

<head>
    <link href="https://fonts.googleapis.com/css?family=Raleway|Roboto|Satisfy" rel="stylesheet">
</head>

<div class="header">
    <h1>fanfic.io</h1>
    <h2>where your wildest stories come true!</h2>
    <div class="user-greeting">
    {% if user.is_authenticated %}
        Hi, {{ user.username }}.
        <a href="{% url 'users:logout' %}">Log out</a>
        <a href="{% url 'works:new_story' %}">Add new story</a>
    {% else %}
        <a href="{% url 'users:login' %}">Log in</a> or <a href="{% url 'users:sign_up' %}">sign up</a>
    {% endif %}
    </div>
</div>

{% block content %}
{% endblock content %}

works/templates/works/get_chapter.html
{% extends 'works/base.html' %}

{% block content %}
<div class="content">
    <h2>{{ chapter.title }}</h2>
    <p>{{ chapter.content }}</p>

    <div class="comments">
        {% if comments %}
            {% for comment in comments %}
                <div class="single-comment">
                    <p><b>{{ comment.author.username }}</b></p>
                    <p>{{ comment.body }}</p>
                </div>
            {% endfor %}
        {% else %}
            <p>No comments yet.</p>
        {% endif %}
    </div>


    {% if user.is_authenticated %}
    <form action="{% url 'works:get_chapter' chapter.of_story.id chapter.number %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button name="submit">Submit</button>
    </form>
    {% else %}
        <p>Only authenticated users may write comments.</p>
    {% endif %}
</div>

<p><a href="{% url 'works:get_story' chapter.of_story.id %}">Take me back</a></p>
{% endblock content %}

works/templates/works/get_character.html
{% extends 'works/base.html' %}
{% load static %}

{% block content %}
<div class="content">
    <img class="character-image" src="{{ character.image.url }}" width="300" alt="image">
    <h2>{{ character.name }}</h2>
    <p>{{ character.description }}</p>
</div>

<p><a href="{% url 'works:get_story' character.of_story.id %}">Take me back</a></p>
{% endblock content %}

works/templates/works/get_story.html
{% extends 'works/base.html' %}

{% block content %}
<div class="content">
    <h2>{{ story.title }}</h2>
    <p>{{ story.description }}</p>
    {% if user.is_authenticated %}
        {% if story not in user.profile.bookmarks.all %}
            <a type="button" href="{% url 'works:add_bookmark' story.id %}">Add bookmark</a>
        {% else %}
            <a type="button" href="{% url 'works:remove_bookmark' story.id %}">Remove bookmark</a>
        {% endif %}
    {% endif %}
    <h3>Chapters:</h3>
    <ol>
        {% for chapter in story.chapter_set.all %}
        <li><a href="{% url 'works:get_chapter' story.id chapter.number %}">{{ chapter.title }}</a></li>
        {% endfor %}

    </ol>
    {% if is_author %}
        <p><a href="{% url 'works:new_chapter' story.id %}">Add new chapter</a></p>
    {% endif %}
    <h3>Characters:</h3>
    <ul>
        {% for character in story.character_set.all %}
           <li><a href="{% url 'works:get_character' story.id character.id %}">{{ character.name }}</a></li>
        {% endfor %}

    </ul>
    {% if is_author %}
        <p><a href="{% url 'works:new_character' story.id %}">Add new character</a></p>
    {% endif %}
</div>

<a href="{% url 'works:index' %}">Take me back</a>
{% endblock content %}

works/templates/works/index.html
{% extends 'works/base.html' %}

{% block content %}
<div class="content">
    <h3>Check out all the stories:</h3>
    {% if stories_list %}
    <ul>
    {% for story in stories_list %}
        <li><a href="{% url 'works:get_story' story.id %}">{{ story.title }}</a> by {{ story.author }}</li>
        <p>{{ story.description }}</p>
    {% endfor %}
    </ul>
{% else %}
    <p>No stories yet.</p>
{% endif %}
</div>
{% endblock content %}

works/templates/works/new_chapter.html
{% extends 'works/base.html' %}

{% block content %}
<h3>Add new chapter to {{ story.title }}</h3>

<form action="{% url 'works:new_chapter' story.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
</form>

<a href="{% url 'works:index' %}">Take me back</a>
{% endblock content %}

works/templates/works/new_character.html
{% extends 'works/base.html' %}

{% block content %}
<h3>Add new chapter to {{ story.title }}</h3>

<form action="{% url 'works:new_character' story.id %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
</form>

<a href="{% url 'works:index' %}">Take me back</a>
{% endblock content %}

works/templates/works/new_story.html
{% extends 'works/base.html' %}

{% block content %}
<h3>Add new story {{ user.username }}</h3>

<form action="{% url 'works:new_story' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Submit</button>
</form>

<a href="{% url 'works:index' %}">Take me back</a>
{% endblock content %}