fanfic_io/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls')),
    path('works/', include('works.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from . import views

app_name = 'main'
urlpatterns = [
    # ...
    path('', views.index, name='index'),
]

users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView

from . import views

app_name = 'users'
urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
    path('<slug:username>/', views.profile, name='profile'),
    path('<slug:username>/works/', views.works, name='works'),
    path('<slug:username>/drafts/', views.drafts, name='drafts'),
    path('<slug:username>/bookmarks/', views.bookmarks, name='bookmarks'),
    path('<slug:username>/edit/', views.edit, name='edit'),
    path('<slug:username>/change_username/', views.change_username, name='change_username'),
    path('<slug:username>/change_password/', views.change_password, name='change_password'),
    path('<slug:username>/change_email/', views.change_email, name='change_email'),
]

works/urls.py
from django.urls import path

from . import views

app_name = 'works'
urlpatterns = [
    # .../works/
    path('', views.IndexView.as_view(), name='index'),
    # .../works/5/
    path('<int:story_id>/', views.get_story, name='get_story'),
    # .../works/5/add_bookmark
    path('<int:story_id>/add_bookmark/', views.add_bookmark, name='add_bookmark'),
    # .../works/5/remove_bookmark
    path('<int:story_id>/remove_bookmark/', views.remove_bookmark, name='remove_bookmark'),
    # .../works/5/chapters/1
    path('<int:story_id>/chapters/<int:chapter_number>/', views.get_chapter, name='get_chapter'),
    # .../works/5/characters/1
    path('<int:story_id>/characters/<int:pk>/', views.CharacterView.as_view(), name='get_character'),
    # .../works/new_story
    path('new_story/', views.new_story, name='new_story'),
    # .../works/5/new_chapter
    path('<int:story_id>/new_chapter/', views.new_chapter, name='new_chapter'),
    # .../works/5/new_character
    path('<int:story_id>/new_character/', views.new_character, name='new_character')
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from works.models import Story


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length=300)
    picture = models.ImageField(upload_to='users_pictures',
                                blank=True,
                                default='empty.jpg')
    bookmarks = models.ManyToManyField(Story)

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

works/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# TODO: make drafts possible - something with published date maybe?
class Story(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    created_date = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Stories"


class Chapter(models.Model):
    of_story = models.ForeignKey(Story, on_delete=models.CASCADE)
    number = models.IntegerField()
    title = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    last_modified = models.DateTimeField(default=timezone.now)
    content = models.TextField()

    def __str__(self):
        return str(self.number) + ". " + self.title

    class Meta:
        ordering = ['number']


class Character(models.Model):
    name = models.CharField(max_length=100)
    of_story = models.ForeignKey(Story, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='character_images', blank=True, default='empty.jpg')
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    of_chapter = models.ForeignKey(Chapter,
                                   on_delete=models.CASCADE,
                                   related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return self.body[:50]

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

from .models import Profile


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=250)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email', 'password1']
        labels = {
            'first_name': 'First name:',
            'last_name': 'Last name:',
            'username': 'Username:',
            'email': 'E-mail address:',
            'password1': 'Password1:'
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['picture', 'description']

works/forms.py
from django import forms

from .models import Story, Chapter, Character, Comment


class StoryForm(forms.ModelForm):
    class Meta:
        model = Story
        fields = ['title', 'description']
        labels = {
            'title': 'Title:',
            'description': 'Short description of the story:'
        }


class ChapterForm(forms.ModelForm):
    class Meta:
        model = Chapter
        fields = ['title', 'content']
        labels = {
            'title': 'Title:',
            'content': ''
        }


class CharacterForm(forms.ModelForm):
    class Meta:
        model = Character
        fields = ['name', 'image', 'description']
        labels = {
            'name': 'Full name:',
            'image': 'Picture:',
            'description': 'Short info about the character:'
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']
        labels = {
            'body': ''
        }

users/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.db import transaction

from .forms import SignUpForm, UserForm, ProfileForm
from .models import Profile


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def sign_up(request):
    if request.method != 'POST':
        form = SignUpForm()
    else:
        form = SignUpForm(data=request.POST)

        if form.is_valid():
            new_user = form.save(commit=False)
            '''new_user.email = form.cleaned_data['email']
            new_user.first_name = form.cleaned_data['first_name']
            new_user.last_name = form.cleaned_data['last_name']'''
            new_user.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=form.cleaned_data['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('works:index'))

    context = {'form': form}
    return render(request, 'users/sign_up.html', context)


def profile(request, username):
    displayed_user = get_object_or_404(User, username=username)
    user_profile = get_object_or_404(Profile, user=displayed_user)
    user_works_list = displayed_user.story_set.all()[:3]
    user_bookmarks_list = user_profile.bookmarks.all()[:3]
    context = {
        'displayed_user': displayed_user,
        'user_profile': user_profile,
        'user_works_list': user_works_list,
        'user_bookmarks_list': user_bookmarks_list,
        'owner': displayed_user == request.user
    }
    return render(request, 'users/profile.html', context)


def works(request, username):
    author = get_object_or_404(User, username=username)
    works_list = author.story_set.all()
    context = {
        'author': author,
        'works_list': works_list,
    }
    return render(request, 'users/works.html', context)


# TODO: drafts view
def drafts(request, username):
    return HttpResponse('List of unposted works written by ' + username)


def bookmarks(request, username):
    owner = get_object_or_404(User, username=username)
    bookmarks_list = owner.profile.bookmarks.all()
    context = {
        'owner': owner,
        'bookmarks': bookmarks_list
    }
    return render(request, 'users/bookmarks.html', context)


@login_required
@transaction.atomic
def edit(request, username):
    user = get_object_or_404(User, username=username)
    if user != request.user:
        raise Http404
    if request.method != 'POST':
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)
    else:
        user_form = UserForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            return HttpResponseRedirect(reverse('users:profile', args=[username]))
    context = {
        'user': user,
        'user_form': user_form,
        'profile_form': profile_form
    }
    return render(request, 'users/edit.html', context)


# TODO: change_username view
def change_username(request, username):
    return HttpResponse('Change your username ' + username + ' (just not yet, okay?)')


# TODO: change_password view
def change_password(request, username):
    return HttpResponse('Change your password ' + username + ' (just not yet, okay?)')


# TODO: change_email view
def change_email(request, username):
    return HttpResponse('Change your email ' + username + ' (just not yet, okay?)')

works/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Story, Chapter, Character
from .forms import StoryForm, ChapterForm, CharacterForm, CommentForm


class IndexView(generic.ListView):
    template_name = 'works/index.html'
    context_object_name = 'stories_list'

    def get_queryset(self):
        return Story.objects.filter().order_by('-created_date')


class StoryView(generic.DetailView):
    model = Story
    template_name = 'works/get_story.html'


class ChapterView(generic.DetailView):
    model = Chapter
    template_name = 'works/get_chapter.html'


def get_story(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if request.method == 'POST':
        request.user.profile.bookmarks.add(story)
        print('Story successful added to bookmarks!')
    context = {
        'story': story,
        'is_author': request.user == story.author
    }
    return render(request, 'works/get_story.html', context)


@login_required
def add_bookmark(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    request.user.profile.bookmarks.add(story)
    return HttpResponseRedirect(reverse('works:get_story', args=[story_id]))


@login_required
def remove_bookmark(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    request.user.profile.bookmarks.remove(story)
    return HttpResponseRedirect(reverse('works:get_story', args=[story_id]))


def get_chapter(request, story_id, chapter_number):
    chapter = get_object_or_404(Chapter,
                                of_story=story_id,
                                number=chapter_number)
    comments = chapter.comments.filter(active=True)
    if request.method != 'POST':
        comment_form = CommentForm()
    else:
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.of_chapter = chapter
            new_comment.author = request.user
            new_comment.save()
            return HttpResponseRedirect(reverse('works:get_chapter', args=[story_id,
                                                                           chapter_number]))
    context = {
        'chapter': chapter,
        'comments': comments,
        'comment_form': comment_form
    }
    return render(request, 'works/get_chapter.html', context)


class CharacterView(generic.DetailView):
    model = Character
    template_name = 'works/get_character.html'


@login_required
def new_story(request):
    if request.method != 'POST':
        form = StoryForm()
    else:
        form = StoryForm(request.POST)
        if form.is_valid():
            story = form.save(commit=False)
            story.author = request.user
            story.save()
            return HttpResponseRedirect(reverse('works:index'))

    context = {
        'form': form
    }
    return render(request, 'works/new_story.html', context)


@login_required
def new_chapter(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if story.author != request.user:
        raise Http404
    if request.method != 'POST':
        form = ChapterForm()
    else:
        form = ChapterForm(request.POST)
        if form.is_valid():
            chapter = form.save(commit=False)
            chapter.of_story = story
            chapter.number = Chapter.objects.filter(of_story=story_id).count() + 1
            chapter.save()
            return HttpResponseRedirect(reverse('works:get_story', args=[chapter.of_story.id]))

    context = {
        'form': form,
        'story': story
    }
    return render(request, 'works/new_chapter.html', context)


@login_required
def new_character(request, story_id):
    story = get_object_or_404(Story, id=story_id)
    if story.author != request.user:
        raise Http404
    if request.method != 'POST':
        form = CharacterForm()
    else:
        form = CharacterForm(request.POST, request.FILES)
        if form.is_valid():
            character = form.save(commit=False)
            character.of_story = story
            character.save()
            return HttpResponseRedirect(reverse('works:get_story', args=[character.of_story.id]))

    context = {
        'form': form,
        'story': story
    }
    return render(request, 'works/new_character.html', context)

users/templates/users/bookmarks.html
{% extends 'works/base.html' %}

{% block content %}
<div class="content">
    <h3>{{ bookmarks.count }} bookmarks by {{ owner.username }}</h3>
    <ul>
        {% for bookmark in bookmarks %}
            <ol><a href="{% url 'works:get_story' bookmark.id %}">{{ bookmark.title }}</a> </ol>
        {% endfor %}
    </ul>

</div>
{% endblock content %}

users/templates/users/edit.html
<form method="POST" action="{% url 'users:edit' user.username %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button name="submit">Update</button>
    <input type="hidden" name="next" value="{% url 'users:profile' user.username %}">
</form>

users/templates/users/login.html
{% if form.errors %}
    <p>Login and/or password incorrect. Try again.</p>
{% endif %}

<form method="POST" action="{% url 'users:login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Log in</button>
    <input type="hidden" name="next" value="{% url 'works:index' %}">
</form>

users/templates/users/profile.html
{% extends 'works/base.html' %}
{% load static %}

{% block content %}
<div class="content">
    {% if owner %}
        <ul class="nav">
            <li><a href="{% url 'users:drafts' user.username %}">Your drafts</a></li>
            <li><a href="{% url 'users:bookmarks' user.username %}">Your bookmarks</a></li>
            <li><a href="{% url 'users:change_username' user.username %}">Change username</a></li>
            <li><a href="{% url 'users:change_password' user.username %}">Change password</a></li>
            <li><a href="{% url 'users:change_email' user.username %}">Change email</a></li>
        </ul>
    {% endif %}

    <h2>{{ displayed_user.username }}</h2>
    <img class="user-image" src="{{ user_profile.picture.url }}" width="300" alt="image">
    <p><b>First name: </b>{{ displayed_user.first_name }}</p>
    <p><b>Last name: </b>{{ displayed_user.last_name }}</p>
    <p><b>Email address: </b>{{ displayed_user.email }}</p>
    <p><b>About me:</b>{{ user_profile.description }}</p>

    <h3>Recent works by {{ displayed_user.username }}</h3>
    {% if user_works_list %}
        <ul>
        {% for work in user_works_list %}
            <li><a href="{% url 'works:get_story' work.id %}">{{ work.title }}</a></li>
        {% endfor %}
        </ul>
        <a href="{% url 'users:works' displayed_user.username %}">All stories</a>
    {% else %}
        <p>This user has not posted any stories yet.</p>
    {% endif %}

    <h3>Recent bookmarks by {{ displayed_user.username }}</h3>
    {% if user_bookmarks_list %}
        <ul>
        {% for work in user_bookmarks_list %}
            <li><a href="{% url 'works:get_story' work.id %}">{{ work.title }}</a></li>
        {% endfor %}
        </ul>
        <a href="{% url 'users:bookmarks' displayed_user.username %}">All bookmarks</a>
    {% else %}
        <p>This user has not bookmarked any stories yet.</p>
    {% endif %}
</div>


<a href="{% url 'main:index' %}">Take me back</a>
{% endblock content %}

users/templates/users/register.html
<form method="POST" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'works:index' %}">
</form>

users/templates/users/sign_up.html
<form method="POST" action="{% url 'users:sign_up' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">Register</button>
    <input type="hidden" name="next" value="{% url 'works:index' %}">
</form>

users/templates/users/update_profile.html
<form method="POST" action="{% url 'users:update_profile' user.username %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    <button name="submit">Update</button>
    <input type="hidden" name="next" value="{% url 'users:profile' user.username %}">
</form>

users/templates/users/user_profile.html
<div class="header">
    <h1>fanfic.io</h1>
</div>

{% load static %}


<div class="content">
    <h2>{{ user.username }}</h2>
    <img class="user-image" src="{{ user_profile.picture.url }}" width="300" alt="image">
    <p><b>First name: </b>{{ user.first_name }}</p>
    <p><b>Last name: </b>{{ user.last_name }}</p>
    <p><b>Email address: </b>{{ user.email }}</p>
    <p><b>About me:</b>{{ user_profile.description }}</p>

    <h3>Works by {{ user.username }}</h3>
    {% if user_works_list %}
        <ul>
        {% for work in user_works_list %}
            <li><a href="{% url 'works:get_story' work.id %}">{{ work.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>This user has not posted any stories yet.</p>
    {% endif %}
</div>


<a href="{% url 'main:index' %}">Take me back</a>

users/templates/users/works.html
{% extends 'works/base.html' %}

{% block content %}
<div class="content">
    <h3>Works by {{ author.username }}</h3>
    {% for work in works_list %}
        <div class="work-short-description">
            <h4>{{ work.title }}</h4>
            {% for character in work.character_set.all %}
                {{ character.name }}
            {% endfor %}
            <p>{{ work.description }}</p>
            <a href="{% url 'works:get_story' work.id %}">Read</a>
        </div>
    {% endfor %}
</div>
{% endblock content %}